# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
platform :ios, '8.0'
use_frameworks!

target 'Week1' do
    pod 'AFNetworking', '~> 2.5'
    pod 'SwiftyJSON', '~> 2.1'
end

target 'Week1Tests' do

end

